// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNJqWZed8nJ8g6LlTOaPub6PoTYqktm3Y',
    appId: '1:398322299818:web:4884e35c8d440ef161f1d3',
    messagingSenderId: '398322299818',
    projectId: 'countdowns-d18b0',
    authDomain: 'countdowns-d18b0.firebaseapp.com',
    storageBucket: 'countdowns-d18b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlejWETLwADlSm937JuCT9zV2u06lmze4',
    appId: '1:398322299818:android:c77ac402afae603761f1d3',
    messagingSenderId: '398322299818',
    projectId: 'countdowns-d18b0',
    storageBucket: 'countdowns-d18b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYRgDMFOBwXShoCorlD2MoliPA7AyfaQw',
    appId: '1:398322299818:ios:c60f413d53d3ca8561f1d3',
    messagingSenderId: '398322299818',
    projectId: 'countdowns-d18b0',
    storageBucket: 'countdowns-d18b0.appspot.com',
    iosBundleId: 'com.example.countdowntimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYRgDMFOBwXShoCorlD2MoliPA7AyfaQw',
    appId: '1:398322299818:ios:60a12d427f22285661f1d3',
    messagingSenderId: '398322299818',
    projectId: 'countdowns-d18b0',
    storageBucket: 'countdowns-d18b0.appspot.com',
    iosBundleId: 'com.example.countdowntimer.RunnerTests',
  );
}
